name: CI Notify

on:
  push:
    branches:
      - Actions
  workflow_run:
    workflows: [ "Build and Test" ]
    types: [ completed ]

jobs:
  slack-notifications:
    runs-on: ubuntu-latest
    if: ${{ always() }}
    steps:
      - name: send a slack SUCCESS message
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        uses: docker://technosophos/slack-notify
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_USERNAME: "Github Actions Slackbot"
          SLACK_TITLE: "Workflow number ${{ github.run_number }}"
          SLACK_MESSAGE: "Finished Successfully on Attempt #${{ github.run_attempt }}"
      - name: send a slack FAILED message
        if: needs.run-shell-commands.result != 'success'
        uses: docker://technosophos/slack-notify
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_USERNAME: "Github Actions Slackbot"
          SLACK_TITLE: "Workflow number ${{ github.run_number }}"
          SLACK_MESSAGE: "CI failed on attempt #${{ github.run_attempt }}"