name: Build and Test

on:
  push:
    branches:
      - Actions

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          ref: Actions
      - name: build images
        run: cd application && docker build -t test_backend .
      - uses: isbang/compose-action@v1.2.0
        with:
          compose-file: "./application/docker-compose.yaml"
      - name: show services
        run: docker ps
      - name: build test container
        run: cd test_env && docker build -t api-test .
      - name: reach localhost
        run: curl localhost:80
      - name: run E2E
        run: docker run api-test localhost