name: Build and Test

on:
  push:
    branches:
      - Actions

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          ref: Actions
      - name: build images
        run: cd application && docker build -t test_backend .
      - uses: isbang/compose-action@v1.2.0
        with:
          compose-file: "docker-compose.yml"
  tests:
    runs-on: ubuntu-latest
    needs: deployment
    steps:
      - name: build test container
        run: docker build -t api-test .
      - name: run E2E
        run: docker run api-test localhost:80