name: Build and Test

on:
  push:
    branches:
      - Actions

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          ref: Actions
      - name: build images
        run: cd application && docker build -t test_backend .
  deployment:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: isbang/compose-action@v1.2.0
          with:
            compose-file: "./application/docker-compose.yml"
            up-flags:
              - --build
  tests:
    runs-on: ubuntu-latest
    container:
      image: python:3.11-rc-alpine3.16
      volumes:
        - ./test_env/:/test
    needs: deployment
    steps:
      - name: move to container folder
        run: cd /test
      - name: pip install
        run: pip install -R requirements.txt
      - name: run E2E
        run: python E2E.py localhost:80